# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Mod Properties
archive_name = StructureControlUtility
mod_id=structurecontrolutility
mod_group=com.mactso.structurecontrolutility
mod_version=0.2.3
mc_version = 1.21.11
forge_version = 61.0.5
mappings_channel=official
mappings_version=1.21.11

