# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties
mod_name=Structure Control Utility
mod_id=structurecontrolutility
mod_group=com.mactso.structurecontrolutility
mod_version=0.2.1
minecraft_version=1.21.5
forge_version=55.0.4
mapping_channel=official
mapping_version=1.21.5



mod_authors=MacTso, Lupicus