# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
mod_name=Structure Control Utility
mod_id=structurecontrolutility
mod_group_id=com.mactso.structurecontrolutility
mod_version=0.2.2

minecraft_version=1.21.1
forge_version=52.0.3
mapping_channel=official
mapping_version=1.21.1

mod_authors=MacTso, Lupicus