modLoader="javafml"
loaderVersion="[56,)"
license="MIT License"
[[mods]]
modId="structurecontrolutility"
version="${file.jarVersion}"
displayName="Structure Control Utility Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-control-utility"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Structure Control Utility Mod.'
[[dependencies.structurecontrolutility]]
    modId="forge"
    mandatory=true
    versionRange="[57,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.structurecontrolutility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.7,1.22)"
    ordering="NONE"
    side="SERVER"
